# Generated by Django 5.2.5 on 2025-09-02 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_conducteurs', '0002_remove_evaluation_unique_evaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluateur',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte utilisateur Django associé à cet évaluateur', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
